API_FW:
  repository: 42crunch/apifirewall
  tag: latest # Should be a fixed version.
  secretname: docker-registry-creds
  pullPolicy: Always
  ServerName: pixi-secured.42crunch.test

API:
  name: protected-api
  schema: http
  pullPolicy: Always
  image: # Container repo
  tag: # Container tag
  port: # Container listening port

registry:
  host: index.docker.io
  username: # <registered_user>
  password: # <registered_password>

#------------------------------------------------------
service:
  type: LoadBalancer
  port: 443

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
