apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apifw-proxy.fullname" . }}-protection-token
  labels:
    app.kubernetes.io/name: {{ template "apifw-proxy.name" . }}
    helm.sh/chart: {{ include "apifw-proxy.chart" . }}
    app.kubernetes.io/managed-by:  {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  PROTECTION_TOKEN: {{ .Values.API_FW.protection_token | b64enc | quote }}