apiVersion: v1
kind: Service
metadata:
  name: {{ include "apifw-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "apifw-proxy.name" . }}
    helm.sh/chart: {{ include "apifw-proxy.chart" . }}
    app.kubernetes.io/managed-by:  {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 443
  selector:
    app.kubernetes.io/name: {{ include "apifw-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}