apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pixi-secured
  labels:

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apifirewall
  replicas: {{ .Values.apifirewall.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during rolling RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apifirewall
{{ include "protected-pixi.labels" . | indent 8 }}        
    spec:
      containers:
      - name: {{ .Release.Name }}-apifirewall
        image: {{ .Values.image.repository }}:{{ .Values.image.version }} # replace latest by proper tag in prod environment.
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        args: ["-platform", {{ .Values.platform.url | quote }}]
        command: ["/bin/squire"]
        ports:
          - containerPort: {{ .Values.apifirewall.pod_listen_port | default 8443 }}
        env:
        - name: GUARDIAN_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GUARDIAN_INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GUARDIAN_INSTANCE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GUARDIAN_INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GUARDIAN_INSTANCE_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: PROTECTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-protection-token
              key: PROTECTION_TOKEN    
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        volumeMounts:
        - name: certs-volume
          mountPath: /opt/guardian/conf/ssl
          readOnly: true
      - name: {{ .Release.Name }}-pixi
        image: {{ .Values.pixiapp.repository }}:{{ .Values.pixiapp.version }} 
        imagePullPolicy: {{ .Values.pixiapp.pullPolicy | quote }}    
      volumes:
      - name: certs-volume
        secret:
          secretName: {{ .Release.Name }}-firewall-tls
