---
# Secure Deployment - LoadBalancer definition for 42Crunch Firewall.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pixi
    role: public
  name: pixi-secured
spec:
  type: LoadBalancer
  ports:
  - name: firewall
    port: 443
    targetPort: 443
  selector:
    app: apifirewall

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixi-secured
spec:
  selector:
    matchLabels:
      app: apifirewall
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during rolling RollingUpdate
  template:
    metadata:
      labels:
        app: apifirewall
    spec:
      containers:
      - name: apifirewall
        image: '42crunch/apifirewall:latest'  # replace latest by proper tag in prod environment.
        imagePullPolicy: Always
        ports:
          - containerPort: 443
        env:
        - name: GUARDIAN_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GUARDIAN_INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PROTECTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: generic-pixi-protection-token
              key: PROTECTION_TOKEN
        envFrom:
        - configMapRef:
            name: firewall-props
        volumeMounts:
        - name: certs-volume
          mountPath: /opt/guardian/conf/ssl
          readOnly: true
      - name: pixiapp
        image: 42crunch/pixi:app_v2
        imagePullPolicy: Always
      volumes:
        - name: certs-volume
          secret:
            secretName: firewall-certs
