API_FW:
  repository: 42crunch/apifirewall
  tag: latest
  secretname: docker-registry-creds
  pullPolicy: Always
  TargetSchema: # <Target schema 'http ot https'. Expected http>
  protection_token: # <obtained_from_platform>
  LocalServer: # <Access URL. Should match_your_certs>


registry:
  host: index.docker.io
  username: # <registered_user>
  password: # <registered_password>

#------------------------------------------------------
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

service:
  type: LoadBalancer
  port: 443