apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-protection-token
  labels:
{{ include "protected-pixi.labels" . | indent 4 }}
type: Opaque
data:
  PROTECTION_TOKEN: {{ .Values.apifirewall.protection_token | b64enc | quote }}