apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pixidb.fullname" . }}
  labels:
    app: {{ include "pixidb.name" . }}
    chart: {{ include "pixidb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pixidb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pixidb
        release: {{ .Release.Name }}
        forceupdate: "{{ .Release.Time.Seconds }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.secretname }}
      containers:
        - name: pixidb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
