apiVersion: v1
kind: Service
metadata:
  # name: {{ template "pixidb.fullname" . }}
  name: pixidb
  labels:
    app: {{ include "pixidb.name" . }}
    chart: {{ include "pixidb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: Local
  {{end}}
  ports:
    - name: mongodb
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: pixidb
    release: {{ .Release.Name }}