{{- define "docker-registry-creds" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry.host (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apifw-sidecar.fullname" . }}-registry-creds
  labels:
    app.kubernetes.io/name: {{ template "apifw-sidecar.name" . }}
    helm.sh/chart: {{ include "apifw-sidecar.chart" . }}
    app.kubernetes.io/managed-by:  {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "docker-registry-creds" . }}