# replace the FROM image source by the one you need 
# 42crunch/apifirewall:v1.0.1-preview for us.42crunch.cloud platform
# 42crunch/apifirewall:latest for platform.42crunch.com platform (community)
FROM 42crunch/apifirewall:latest
COPY ./etc/tls/*.pem /opt/guardian/conf/ssl/