apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pixiapp.fullname" . }}
  labels:
    app: {{ include "pixiapp.name" . }}
    chart: {{ include "pixiapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pixiapp
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pixiapp
        release: {{ .Release.Name }}
        forceupdate: "{{ .Release.Time.Seconds }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: pixiapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ui
              containerPort: {{ .Values.service.ui_port }}
              protocol: TCP
            - name: api
              containerPort: {{ .Values.service.api_port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
