apiVersion: v1
kind: Service
metadata:
  name: pixiapp
  labels:
    app: {{ include "pixiapp.name" . }}
    chart: {{ include "pixiapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: Local
  {{end}}
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.service.ui_port }}
      targetPort: {{ .Values.service.ui_port }}
    - name: api
      protocol: TCP
      port: {{ .Values.service.api_port }}
      targetPort: {{ .Values.service.api_port }}
  selector:
    app: pixiapp
    release: {{ .Release.Name }}